# Doctiling self-host installer (Windows).
#   irm https://raw.githubusercontent.com/doctiling/releases/main/install.ps1 | iex
# Installs the latest GitHub release + a pinned Node runtime under
# %LOCALAPPDATA%\Doctiling, generates every secret, registers a logon task.
$ErrorActionPreference = 'Stop'

$Repo = 'doctiling/releases'
$NodeVersion = '20.18.1'
$Home_ = Join-Path $env:LOCALAPPDATA 'Doctiling'
$Port = if ($env:DOCTILING_PORT) { $env:DOCTILING_PORT } else { '3000' }

function Say($msg) { Write-Host "[doctiling] $msg" -ForegroundColor Green }

New-Item -ItemType Directory -Force -Path $Home_, "$Home_\data", "$Home_\logs", "$Home_\bin" | Out-Null

# --- Node runtime -------------------------------------------------------------
$NodeDir = Join-Path $Home_ "node-v$NodeVersion"
$NodeExe = Join-Path $NodeDir 'node.exe'
if (-not (Test-Path $NodeExe)) {
  Say "Downloading Node $NodeVersion…"
  $arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'x64' }
  $zip = "node-v$NodeVersion-win-$arch.zip"
  Invoke-WebRequest "https://nodejs.org/dist/v$NodeVersion/$zip" -OutFile "$Home_\$zip"
  Expand-Archive "$Home_\$zip" -DestinationPath $Home_ -Force
  Rename-Item "$Home_\node-v$NodeVersion-win-$arch" $NodeDir
  Remove-Item "$Home_\$zip"
}

# --- App release --------------------------------------------------------------
Say 'Fetching latest release…'
$release = Invoke-RestMethod "https://api.github.com/repos/$Repo/releases/latest"
$tag = $release.tag_name
$AppDir = Join-Path $Home_ "app-$tag"
if (-not (Test-Path $AppDir)) {
  Say "Downloading Doctiling $tag…"
  Invoke-WebRequest "https://github.com/$Repo/releases/download/$tag/doctiling-standalone.tar.gz" -OutFile "$Home_\app.tar.gz"
  New-Item -ItemType Directory -Force -Path $AppDir | Out-Null
  tar -xzf "$Home_\app.tar.gz" -C $AppDir
  Remove-Item "$Home_\app.tar.gz"
}
$Current = Join-Path $Home_ 'current'
if (Test-Path $Current) { Remove-Item $Current -Force -Recurse:$false }
New-Item -ItemType Junction -Path $Current -Target $AppDir | Out-Null

# --- .env: generate every key the app needs ----------------------------------
$EnvFile = Join-Path $Home_ '.env'
if (-not (Test-Path $EnvFile)) {
  Say 'Generating secrets (.env)…'
  $authSecret = & $NodeExe -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
  $webhookKey = & $NodeExe -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
  $vapid = & $NodeExe "$Current\scripts\self-host\generate-vapid.mjs" 2>$null
  $dbPath = ($Home_ -replace '\\', '/') + '/data/app.db'
  @"
# Generated by the Doctiling self-host installer. Safe defaults for a
# single-user laptop install; everything stays on this machine.
SELF_HOSTED=true
HOSTNAME=127.0.0.1
PORT=$Port
TURSO_DATABASE_URL=file:$dbPath
AUTH_SECRET=$authSecret
AUTH_TRUST_HOST=true
WEBHOOK_HEADERS_KEY=$webhookKey
AI_CONFIG_UI_ENABLED=true

# Local AI (LM Studio / Ollama).
LLM_PROVIDER=local
LLM_MODEL=llama-3.1-8b-instruct
LLM_BASE_URL=http://127.0.0.1:1234/v1
EMBEDDING_PROVIDER=local
OPENAI_EMBED_MODEL=text-embedding-nomic-embed-text-v1.5

# Optional cloud keys — leave empty to stay fully local.
# ANTHROPIC_API_KEY=
# GEMINI_API_KEY=
# OPENAI_API_KEY=
"@ | Set-Content -Encoding UTF8 $EnvFile
  if ($vapid) {
    $parts = $vapid.Trim() -split ' '
    Add-Content $EnvFile "`n# Web push (notifications when the window is hidden)"
    Add-Content $EnvFile "NEXT_PUBLIC_VAPID_PUBLIC_KEY=$($parts[0])"
    Add-Content $EnvFile "VAPID_PRIVATE_KEY=$($parts[1])"
  }
}

# --- Runner + logon task -------------------------------------------------------
$Runner = Join-Path $Home_ 'bin\doctiling-run.ps1'
@"
`$ErrorActionPreference = 'Continue'
Set-Location '$Current'
Get-Content '$EnvFile' | ForEach-Object {
  if (`$_ -match '^\s*([A-Z0-9_]+)=(.*)$') { [Environment]::SetEnvironmentVariable(`$Matches[1], `$Matches[2]) }
}
& '$NodeExe' '$Current\scripts\self-host\migrate.mjs' *>> '$Home_\logs\doctiling.log'
& '$NodeExe' '$Current\server.js' *>> '$Home_\logs\doctiling.log'
"@ | Set-Content -Encoding UTF8 $Runner

$action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$Runner`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
Register-ScheduledTask -TaskName 'Doctiling' -Action $action -Trigger $trigger -Force | Out-Null
Start-ScheduledTask -TaskName 'Doctiling'
Say 'Registered logon task "Doctiling".'

Say "Waiting for the app on http://127.0.0.1:$Port …"
$ok = $false
for ($i = 0; $i -lt 60; $i++) {
  try { Invoke-WebRequest "http://127.0.0.1:$Port" -UseBasicParsing -TimeoutSec 2 | Out-Null; $ok = $true; break } catch { Start-Sleep 1 }
}
if (-not $ok) { throw "The app did not come up; check $Home_\logs\doctiling.log" }

$lang = if ((Get-Culture).TwoLetterISOLanguageName -eq 'es') { 'es' } else { 'en' }
$appUrl = "http://127.0.0.1:$Port/$lang/signin"
Say "Done. Opening $appUrl — install it as an app from your browser."
Start-Process $appUrl
